[tool.poetry]
name = "learning-cognito-py"
version = "0.1.0"
description = "ğŸ›ğŸ›ğŸ› Pythonã§Cognitoã®èªè¨¼ãƒ•ãƒ­ãƒ¼ã‚’å®Ÿè£…ã—ãŸã‚µãƒ³ãƒ—ãƒ«ã§ã™ï¼"
authors = ["osawa-koki <koki@osawa.dev>"]
license = "Apache-2.0"
readme = "README.md"
packages = [{include = "learning_cognito"}]

[tool.poetry.dependencies]
python = "^3.11"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
