[tool.poetry]
name = "learning-cognito-py"
version = "0.1.0"
description = "ğŸ›ğŸ›ğŸ› Pythonã§Cognitoã®èªè¨¼ãƒ•ãƒ­ãƒ¼ã‚’å®Ÿè£…ã—ãŸã‚µãƒ³ãƒ—ãƒ«ã§ã™ï¼"
authors = ["osawa-koki <koki@osawa.dev>"]
license = "Apache-2.0"
readme = "README.md"
packages = [{include = "learning_cognito"}]

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.104.1"
uvicorn = {extras = ["standard"], version = "^0.24.0.post1"}

[tool.poetry.group.dev.dependencies]
pylint = "^3.0.2"
autopep8 = "^2.0.4"
isort = "^5.12.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
